apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: api-frontend
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: api-frontend
    app.kubernetes.io/part-of: api-frontend
  name: api-frontend
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: api-frontend
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: api-frontend
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rh-platform-experien-tenant/api-frontend/api-frontend@sha256:829ba0c95f0cebbf089045b3b749443b11c70e3ab8adc571997e8dc819b27bbe
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
